hash-format = "sha256"

[[files]]
file = ".packwizml.cache"
hash = "73fe8f970bbf74213b34b45f806312f439403968e99ebb621a38e0f062985052"

[[files]]
file = "LICENSE"
hash = "1eb85fc97224598dad1852b5d6483bbcf0aa8608790dcc657a5a2a761ae9c8c6"

[[files]]
file = "README.md"
hash = "46c490f021a685f07cb51ae3d5f0f75cc8863f993c82b957bc888146f5dd035a"

[[files]]
file = "modlist.md"
hash = "eb87630487c73a9ce4d80b49dd1919f6049fb9341be85fcbb102040b23e2ac72"

[[files]]
file = "mods/animatica.pw.toml"
hash = "73386e4a41baab1188f2c594ac9efad42ccbb3c02934d21cc86461b616121954"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "939d73cc5d76ad6c49de09d586ea3bfca1959c54c2518948c495e3114e4d5cb7"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "39288231de229a526ae51f44ba357a6ac472ba598dd74fea2b0eaaf868714669"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "753859b58aa7a674785b3ec5a8080c2142209a50185cc3dd5ab90c7c6a38f5ee"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "d2bb03cee21d84e8e72fccc06cc8afbd6760674a7b8629a3fcba98e24503008e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "955b5160e856fbc93b615ad021e78421383177db29a1b0bc451e2840ad659f79"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "c49d1423a5f2563335fd5719862a861c8ae2c9cbc46598e767c3e2fe1042ecae"
metafile = true

[[files]]
file = "mods/completeconfig.pw.toml"
hash = "705467dbef3e51481597a5ba871aa24a6aedac55791ae04e8c3dd77ea2ae55fd"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "749bf88d67ff9ddf272dc48d82402dd61ea2812238dfca4feb1fd78440675456"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "cb14cb30c723d1ed83f1d612b61b12134ea3a39fcff3ae02c2aedc2c1aa12a67"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "e9ae0492006c9a6bc309bee3658dcc6ebb96d213f74f6285bac4ae26ffc67631"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "004dbebb72fb7b4afaa12797a18c0871b78da1cc930ee0a9e65a485a99d6232b"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "1629a5389009c1fb824d16f317e84980b536193fbd193fc0efe1ef9686531844"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "3d3c9d0226ba1b2d69e096989644a9b721f8031a3f5ebabca3540102861d23c3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "9ae76046167e451e37eb846a72b8ff2b04b997767b717b37f4c8c586f08a5ef6"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "0b0b7d2de5e46b9032ae84b25f554839e7fabfeab7bd8bcb48392b940e112f38"
metafile = true

[[files]]
file = "mods/fastopenlinksandfolders.pw.toml"
hash = "8a2498e02882121efeac1e1836e93ecaa06370828117295a589163de4008c46f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "432ff6dab148ec6b17440c2c83d2f62c1ad5eae3cbc6edc8126787aa5e8c13c9"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e516d6d036f6d407a793c3b9a1fc5a8a817b05c9dc9d8677003fb0a512b2bf6f"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "7848466b7f337faf90f5edb14aeed716c398f8abfe091cef7c4894102e2727d4"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a2bb983e5dffe95d1f92ee19a099ed214f9b3d39c4e9f8eb5991a1a3c7735b45"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "2ea587bc28af997f2b93de69af32b8ba0120ce8a2c0e95624a0c55051eb25041"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8fb914c75a06a677721dd1fc880606d790886be9e0b392820dcecb9bb56e0786"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f264c166b22cf93af5e44a3d65931e2a46008d11ee0cd81f209a3af54979a760"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "dc1f47a526f2264dc215437a81668d54c084d5beaaa6cbf6e284b88a59af88b5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f0a7c49ae4417a753722da78046a7513e059e5964e21154f4aef50df6a1d6ed0"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "01efbdcb32ff6e70b6777e26df46bbe3c6c5aecb3e0c81797d234dfad9e0568d"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "6abb2071e06ebda2ee6ceee2a0a469e71d04934069dcd351ed13ccba8b1e4ef7"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "3617f55f5973b7dcaab7ae5098db9f3daf6d5e89123c0a58301333435dda6e03"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "aed75e1420b08394093f029d594ef3e352f3f94789a48dfa549506c1c704a9c5"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b4d8e22f7916c1a2e8be07b708cd02d16bd730e382bb7ca36a615cf3e6782940"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
hash = "eb68f07474889d53f9b81902ad7aca2979604aa6d5102327574b687b1e1c1424"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8bdc3c1b5079b7fbe89f995d1a100e1df8dcf47e73ef089abf444ecc8e320527"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0d539d8bad8493d4196bf5f7bf216d692384f283849fa41a2e5a816a0147673e"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "bd5a6a0ddf6b0f26318524ca0bb2d9a6b393e2d19a6c3107a13e390dda3c1cd7"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c6c963c8c9389d864664aabfd259e9b3909c274b56b2ff1477dac551216b3a28"
metafile = true
